"""Python SDK with mutable authoring and immutable native rendering APIs."""

from ._native import (
    BackendPreference,
    BackendKind,
    BackendFallback,
    Category,
    Diagnostic,
    Editor,
    Frame,
    FrameRate,
    FrameRenderError,
    RenderError,
    CancelledError,
    GraphicsBackend,
    InspectAssets,
    InspectAudio,
    InspectAudioClip,
    InspectAudioEffect,
    InspectAudioGainKeyframe,
    InspectAudioTrack,
    InspectionReport,
    InspectOutput,
    PreflightOptions,
    PreflightReport,
    Project as _NativeProject,
    ProjectError,
    PreparationError,
    PreparationReport,
    PreparationTimings,
    PrepareOptions,
    PreparedProject,
    PreparedProjectBusyError,
    PreparedVideoRenderRequest,
    RenderRequest,
    CancellationToken,
    RenderEvent,
    RenderResult,
    RenderTimingScope,
    RenderTimings,
    RenderPerformance,
    RenderFailureContext,
    RenderFailureStage,
    AdapterDeviceType,
    AdapterInfo,
    PixelFormat,
    Severity,
    ValidationReport,
    VideoEditorError,
    native_version,
)

# Mutable high-level editor model. ``ProjectSnapshot`` below remains the
# immutable native compatibility name used by the legacy package.
from .editor import Composition, CompositionLayer, Layer, Project as Project
from .audio import (
    AudioClip,
    AudioEffectStack,
    AudioFadeCurve,
    AudioGainInterpolation,
    AudioGainKeyframe,
    AudioTimeline,
    AudioTrack,
    BassBoost,
    ParametricEq,
    PlaybackSpeed,
)
from .sources import Image, Source
from .flashes import Flash, FlashCollection
from .presets import Preset, PresetCollection
from .transitions import (
    Animate,
    Crossfade,
    CustomTransition,
    DirectionalPush,
    PushDown,
    PushLeft,
    PushRight,
    PushUp,
    TransitionDefinition,
    TransitionPlacement,
    TransitionCollection,
    ZoomCrossfade,
    ZoomIn,
    ZoomOut,
    TransitionLayer,
)
from .properties import (
    BindablePointProperty,
    BindableScalarProperty,
    CropProperty,
    PointProperty,
    ScalarBindingTarget,
    ScalarProperty,
    SignalBinding,
    SignalOperation,
    Transform,
)
from .signals import MasterAudioSignals, ScalarSignal
from .effects import (
    ActiveInterval,
    Bloom,
    Brightness,
    CameraShake,
    ChromaticAberration,
    ColorAdjust,
    Contrast,
    DirectionalBlur,
    Effect,
    EffectStack,
    GaussianBlur,
    Glow,
    MotionBlur,
    Saturation,
    Sharpen,
    Tint,
    Vignette,
    ZoomBlur,
    ZoomBlurDirection,
)
from .authoring.values import BlendMode, Crop, CubicBezier, Interpolation, Point

# Keep the native type available under its stable public snapshot name.
ProjectSnapshot = _NativeProject

__version__ = native_version()

__all__ = [
    "__version__",
    "native_version",
    "BackendPreference",
    "BackendKind",
    "BackendFallback",
    "AdapterDeviceType",
    "AdapterInfo",
    "GraphicsBackend",
    "PixelFormat",
    "Category",
    "Severity",
    "Diagnostic",
    "Editor",
    "Project",
    "ProjectSnapshot",
    "Composition",
    "CompositionLayer",
    "Layer",
    "Source",
    "Image",
    "ScalarProperty",
    "BindableScalarProperty",
    "BindablePointProperty",
    "ScalarBindingTarget",
    "SignalBinding",
    "SignalOperation",
    "PointProperty",
    "CropProperty",
    "Transform",
    "ScalarSignal",
    "MasterAudioSignals",
    "Interpolation",
    "CubicBezier",
    "Point",
    "Crop",
    "BlendMode",
    "PreflightOptions",
    "ValidationReport",
    "PreflightReport",
    "InspectionReport",
    "InspectOutput",
    "InspectAssets",
    "InspectAudio",
    "InspectAudioEffect",
    "InspectAudioTrack",
    "InspectAudioClip",
    "InspectAudioGainKeyframe",
    "PrepareOptions",
    "PreparedProject",
    "PreparationReport",
    "PreparationTimings",
    "FrameRate",
    "Frame",
    "VideoEditorError",
    "ProjectError",
    "PreparationError",
    "FrameRenderError",
    "PreparedProjectBusyError",
    "RenderError",
    "CancelledError",
    "PreparedVideoRenderRequest",
    "RenderRequest",
    "CancellationToken",
    "RenderEvent",
    "RenderResult",
    "RenderTimingScope",
    "RenderTimings",
    "RenderPerformance",
    "RenderFailureContext",
    "RenderFailureStage",
    "AudioClip",
    "AudioEffectStack",
    "AudioFadeCurve",
    "AudioGainInterpolation",
    "AudioGainKeyframe",
    "AudioTimeline",
    "AudioTrack",
    "BassBoost",
    "ParametricEq",
    "PlaybackSpeed",
    "Animate",
    "Crossfade",
    "CustomTransition",
    "TransitionLayer",
    "ZoomCrossfade",
    "DirectionalPush",
    "PushLeft",
    "PushRight",
    "PushUp",
    "PushDown",
    "ZoomIn",
    "ZoomOut",
    "TransitionDefinition",
    "TransitionPlacement",
    "Preset",
    "PresetCollection",
    "Flash",
    "FlashCollection",
    "TransitionCollection",
    "Effect",
    "EffectStack",
    "ActiveInterval",
    "Brightness",
    "Contrast",
    "Saturation",
    "Tint",
    "GaussianBlur",
    "DirectionalBlur",
    "ZoomBlur",
    "ZoomBlurDirection",
    "Glow",
    "Bloom",
    "ChromaticAberration",
    "Vignette",
    "Sharpen",
    "ColorAdjust",
    "CameraShake",
    "MotionBlur",
]
