"""Python SDK with mutable authoring and immutable native rendering APIs."""

from ._native import (
    BackendPreference,
    BackendKind,
    BackendFallback,
    Category,
    Diagnostic,
    Editor,
    Frame,
    FrameRate,
    FrameRenderError,
    RenderError,
    CancelledError,
    GraphicsBackend,
    InspectAssets,
    InspectAudio,
    InspectionReport,
    InspectOutput,
    PreflightOptions,
    PreflightReport,
    Project,
    ProjectError,
    PreparationError,
    PreparationReport,
    PreparationTimings,
    PrepareOptions,
    PreparedProject,
    PreparedProjectBusyError,
    PreparedVideoRenderRequest,
    RenderRequest,
    CancellationToken,
    RenderEvent,
    RenderResult,
    RenderTimingScope,
    RenderTimings,
    RenderPerformance,
    RenderFailureContext,
    RenderFailureStage,
    AdapterDeviceType,
    AdapterInfo,
    PixelFormat,
    Severity,
    ValidationReport,
    VideoEditorError,
    native_version,
)

__version__ = native_version()

__all__ = [
    "__version__", "native_version", "BackendPreference", "BackendKind", "BackendFallback",
    "AdapterDeviceType", "AdapterInfo", "GraphicsBackend", "PixelFormat", "Category", "Severity",
    "Diagnostic", "Editor", "Project", "PreflightOptions", "ValidationReport",
    "PreflightReport", "InspectionReport", "InspectOutput", "InspectAssets", "InspectAudio",
    "PrepareOptions", "PreparedProject", "PreparationReport", "PreparationTimings", "FrameRate", "Frame",
    "VideoEditorError", "ProjectError", "PreparationError", "FrameRenderError", "PreparedProjectBusyError",
    "RenderError", "CancelledError", "PreparedVideoRenderRequest", "RenderRequest", "CancellationToken",
    "RenderEvent", "RenderResult", "RenderTimingScope", "RenderTimings", "RenderPerformance",
    "RenderFailureContext", "RenderFailureStage",
]
