from collections.abc import Mapping
from os import PathLike
from pathlib import Path
from typing import ClassVar, final

__all__ = [
    "BackendPreference", "Category", "Diagnostic", "Editor", "InspectAssets",
    "InspectAudio", "InspectOutput", "InspectionReport", "PreflightOptions",
    "PreflightReport", "Project", "ProjectError", "Severity", "ValidationReport",
    "VideoEditorError", "native_version",
]

class VideoEditorError(Exception):
    # Exception attributes follow normal Python exception mutability. Their
    # tuple and Diagnostic values are immutable.
    kind: str
    diagnostics: tuple[Diagnostic, ...]
    warnings: tuple[Diagnostic, ...]

class ProjectError(VideoEditorError): ...

@final
class BackendPreference:
    AUTO: ClassVar[BackendPreference]
    CPU: ClassVar[BackendPreference]
    WGPU: ClassVar[BackendPreference]
    @property
    def value(self) -> str: ...

@final
class Category:
    USAGE: ClassVar[Category]
    PROJECT: ClassVar[Category]
    SEMANTIC: ClassVar[Category]
    ASSET: ClassVar[Category]
    MEDIA: ClassVar[Category]
    BACKEND: ClassVar[Category]
    RENDER: ClassVar[Category]
    OUTPUT: ClassVar[Category]
    CANCELLATION: ClassVar[Category]
    INTERNAL: ClassVar[Category]
    @property
    def value(self) -> str: ...

@final
class Severity:
    FATAL: ClassVar[Severity]
    WARNING: ClassVar[Severity]
    @property
    def value(self) -> str: ...

@final
class Diagnostic:
    @property
    def code(self) -> str: ...
    @property
    def category(self) -> Category: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def message(self) -> str: ...
    @property
    def pointer(self) -> str | None: ...
    @property
    def related_id(self) -> str | None: ...
    @property
    def hint(self) -> str | None: ...

@final
class Project:
    @classmethod
    def load(cls, path: PathLike[str] | str) -> Project: ...
    @classmethod
    def from_json(cls, text: str, *, base_directory: PathLike[str] | str | None = None) -> Project: ...
    @classmethod
    def from_dict(cls, data: Mapping[str, object], *, base_directory: PathLike[str] | str | None = None) -> Project: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def save(self, path: PathLike[str] | str) -> None: ...
    @property
    def base_directory(self) -> Path: ...
    @property
    def source_path(self) -> Path | None: ...

@final
class PreflightOptions:
    @classmethod
    def for_validation(cls) -> PreflightOptions: ...
    @classmethod
    def for_inspection(cls) -> PreflightOptions: ...
    @classmethod
    def for_preparation(cls, backend: BackendPreference) -> PreflightOptions: ...
    @classmethod
    def for_render(cls, backend: BackendPreference, output: PathLike[str] | str, *, overwrite: bool = False) -> PreflightOptions: ...
    @property
    def kind(self) -> str: ...
    @property
    def backend(self) -> BackendPreference | None: ...
    @property
    def output(self) -> Path | None: ...
    @property
    def overwrite(self) -> bool: ...

@final
class ValidationReport:
    @property
    def is_valid(self) -> bool: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def errors(self) -> tuple[Diagnostic, ...]: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class PreflightReport:
    @property
    def is_ready(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def errors(self) -> tuple[Diagnostic, ...]: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class InspectOutput:
    @property
    def path(self) -> Path: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def frame_rate(self) -> str: ...
    @property
    def duration_mode(self) -> str: ...
    @property
    def duration(self) -> float: ...
    @property
    def total_frames(self) -> int: ...
    @property
    def preview(self) -> bool: ...

@final
class InspectAssets:
    @property
    def images(self) -> int: ...
    @property
    def audio(self) -> int: ...

@final
class InspectAudio:
    @property
    def asset(self) -> str: ...
    @property
    def start(self) -> float: ...
    @property
    def end(self) -> float: ...

@final
class InspectionReport:
    @property
    def project(self) -> Path: ...
    @property
    def name(self) -> str | None: ...
    @property
    def output(self) -> InspectOutput: ...
    @property
    def assets(self) -> InspectAssets: ...
    @property
    def visual_clips(self) -> int: ...
    @property
    def flashes(self) -> int: ...
    @property
    def transitions(self) -> int: ...
    @property
    def audio(self) -> InspectAudio | None: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class Editor:
    def __init__(self) -> None: ...
    def validate(self, project: Project) -> ValidationReport: ...
    def preflight(self, project: Project, options: PreflightOptions) -> PreflightReport: ...
    def inspect(self, project: Project, *, preview: bool = False) -> InspectionReport: ...

def native_version() -> str: ...
