from collections.abc import Mapping
from os import PathLike
from pathlib import Path
from typing import ClassVar, final

__all__ = [
    "BackendPreference", "BackendKind", "BackendFallback", "AdapterDeviceType", "AdapterInfo", "GraphicsBackend", "PixelFormat", "Category", "Diagnostic", "Editor", "InspectAssets",
    "InspectAudio", "InspectOutput", "InspectionReport", "PreflightOptions",
    "PreflightReport", "Project", "ProjectError", "Severity", "ValidationReport",
    "VideoEditorError", "PreparationError", "FrameRenderError", "PreparedProjectBusyError", "PrepareOptions", "PreparedProject", "PreparationReport", "PreparationTimings", "FrameRate", "Frame", "native_version",
]

class VideoEditorError(Exception):
    # Exception attributes follow normal Python exception mutability. Their
    # tuple and Diagnostic values are immutable.
    kind: str
    diagnostics: tuple[Diagnostic, ...]
    warnings: tuple[Diagnostic, ...]

class ProjectError(VideoEditorError): ...
class PreparationError(VideoEditorError): ...
class FrameRenderError(VideoEditorError): ...
class PreparedProjectBusyError(VideoEditorError): ...

@final
class BackendPreference:
    AUTO: ClassVar[BackendPreference]
    CPU: ClassVar[BackendPreference]
    WGPU: ClassVar[BackendPreference]
    @property
    def value(self) -> str: ...

@final
class BackendKind:
    CPU: ClassVar[BackendKind]
    WGPU: ClassVar[BackendKind]
    @property
    def value(self) -> str: ...

@final
class PixelFormat:
    RGBA8: ClassVar[PixelFormat]
    @property
    def value(self) -> str: ...

@final
class AdapterDeviceType:
    DISCRETE_GPU: ClassVar[AdapterDeviceType]
    INTEGRATED_GPU: ClassVar[AdapterDeviceType]
    VIRTUAL_GPU: ClassVar[AdapterDeviceType]
    CPU: ClassVar[AdapterDeviceType]
    OTHER: ClassVar[AdapterDeviceType]
    @property
    def value(self) -> str: ...

@final
class GraphicsBackend:
    VULKAN: ClassVar[GraphicsBackend]
    METAL: ClassVar[GraphicsBackend]
    DX12: ClassVar[GraphicsBackend]
    GL: ClassVar[GraphicsBackend]
    BROWSER_WEBGPU: ClassVar[GraphicsBackend]
    OTHER: ClassVar[GraphicsBackend]
    @property
    def value(self) -> str: ...

@final
class BackendFallback:
    @property
    def code(self) -> str: ...
    @property
    def stage(self) -> str: ...
    @property
    def message(self) -> str: ...

@final
class AdapterInfo:
    @property
    def adapter_name(self) -> str: ...
    @property
    def device_type(self) -> AdapterDeviceType: ...
    @property
    def graphics_backend(self) -> GraphicsBackend: ...
    @property
    def driver_name(self) -> str: ...
    @property
    def driver_info(self) -> str: ...
    @property
    def vendor_id(self) -> int: ...
    @property
    def device_id(self) -> int: ...

@final
class Category:
    USAGE: ClassVar[Category]
    PROJECT: ClassVar[Category]
    SEMANTIC: ClassVar[Category]
    ASSET: ClassVar[Category]
    MEDIA: ClassVar[Category]
    BACKEND: ClassVar[Category]
    RENDER: ClassVar[Category]
    OUTPUT: ClassVar[Category]
    CANCELLATION: ClassVar[Category]
    INTERNAL: ClassVar[Category]
    @property
    def value(self) -> str: ...

@final
class Severity:
    FATAL: ClassVar[Severity]
    WARNING: ClassVar[Severity]
    @property
    def value(self) -> str: ...

@final
class Diagnostic:
    @property
    def code(self) -> str: ...
    @property
    def category(self) -> Category: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def message(self) -> str: ...
    @property
    def pointer(self) -> str | None: ...
    @property
    def related_id(self) -> str | None: ...
    @property
    def hint(self) -> str | None: ...

@final
class Project:
    @classmethod
    def load(cls, path: PathLike[str] | str) -> Project: ...
    @classmethod
    def from_json(cls, text: str, *, base_directory: PathLike[str] | str | None = None) -> Project: ...
    @classmethod
    def from_dict(cls, data: Mapping[str, object], *, base_directory: PathLike[str] | str | None = None) -> Project: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def save(self, path: PathLike[str] | str) -> None: ...
    @property
    def base_directory(self) -> Path: ...
    @property
    def source_path(self) -> Path | None: ...

@final
class PreflightOptions:
    @classmethod
    def for_validation(cls) -> PreflightOptions: ...
    @classmethod
    def for_inspection(cls) -> PreflightOptions: ...
    @classmethod
    def for_preparation(cls, backend: BackendPreference) -> PreflightOptions: ...
    @classmethod
    def for_render(cls, backend: BackendPreference, output: PathLike[str] | str, *, overwrite: bool = False) -> PreflightOptions: ...
    @property
    def kind(self) -> str: ...
    @property
    def backend(self) -> BackendPreference | None: ...
    @property
    def output(self) -> Path | None: ...
    @property
    def overwrite(self) -> bool: ...

@final
class ValidationReport:
    @property
    def is_valid(self) -> bool: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def errors(self) -> tuple[Diagnostic, ...]: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class PreflightReport:
    @property
    def is_ready(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def diagnostics(self) -> tuple[Diagnostic, ...]: ...
    @property
    def errors(self) -> tuple[Diagnostic, ...]: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class InspectOutput:
    @property
    def path(self) -> Path: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def frame_rate(self) -> str: ...
    @property
    def duration_mode(self) -> str: ...
    @property
    def duration(self) -> float: ...
    @property
    def total_frames(self) -> int: ...
    @property
    def preview(self) -> bool: ...

@final
class InspectAssets:
    @property
    def images(self) -> int: ...
    @property
    def audio(self) -> int: ...

@final
class InspectAudio:
    @property
    def asset(self) -> str: ...
    @property
    def start(self) -> float: ...
    @property
    def end(self) -> float: ...

@final
class InspectionReport:
    @property
    def project(self) -> Path: ...
    @property
    def name(self) -> str | None: ...
    @property
    def output(self) -> InspectOutput: ...
    @property
    def assets(self) -> InspectAssets: ...
    @property
    def visual_clips(self) -> int: ...
    @property
    def flashes(self) -> int: ...
    @property
    def transitions(self) -> int: ...
    @property
    def audio(self) -> InspectAudio | None: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...

@final
class PrepareOptions:
    def __new__(cls, *, backend: BackendPreference | None = None) -> PrepareOptions: ...
    @property
    def backend(self) -> BackendPreference: ...

@final
class FrameRate:
    def __new__(cls, numerator: int, denominator: int | None = None) -> FrameRate: ...
    @property
    def numerator(self) -> int: ...
    @property
    def denominator(self) -> int: ...
    @property
    def value(self) -> float: ...

@final
class PreparationTimings:
    @property
    def semantic_validation_ms(self) -> int: ...
    @property
    def preflight_ms(self) -> int: ...
    @property
    def plan_compile_ms(self) -> int: ...
    @property
    def asset_decode_ms(self) -> int: ...
    @property
    def backend_initialization_ms(self) -> int | None: ...
    @property
    def total_ms(self) -> int: ...

@final
class PreparationReport:
    @property
    def requested_backend(self) -> BackendPreference: ...
    @property
    def selected_backend(self) -> BackendKind: ...
    @property
    def fallback(self) -> BackendFallback | None: ...
    @property
    def adapter(self) -> AdapterInfo | None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def frame_rate(self) -> FrameRate: ...
    @property
    def duration_ns(self) -> int: ...
    @property
    def duration_seconds(self) -> float: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def decoded_asset_count(self) -> int: ...
    @property
    def warnings(self) -> tuple[Diagnostic, ...]: ...
    @property
    def timings(self) -> PreparationTimings: ...
    @property
    def supports_single_frame_rendering(self) -> bool: ...

@final
class Frame:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def frame_number(self) -> int: ...
    @property
    def timestamp_ns(self) -> int: ...
    @property
    def timestamp_seconds(self) -> float: ...
    @property
    def pixel_format(self) -> PixelFormat: ...
    def to_bytes(self) -> bytes: ...
    def __bytes__(self) -> bytes: ...

@final
class PreparedProject:
    @property
    def preparation_report(self) -> PreparationReport: ...
    @property
    def supports_single_frame_rendering(self) -> bool: ...
    def render_frame_number(self, frame_number: int) -> Frame: ...
    def render_frame_ns(self, timestamp_ns: int) -> Frame: ...
    def render_frame_seconds(self, seconds: float) -> Frame: ...

@final
class Editor:
    def __init__(self) -> None: ...
    def validate(self, project: Project) -> ValidationReport: ...
    def preflight(self, project: Project, options: PreflightOptions) -> PreflightReport: ...
    def inspect(self, project: Project, *, preview: bool = False) -> InspectionReport: ...
    def prepare(self, project: Project, options: PrepareOptions | None = None) -> PreparedProject: ...

def native_version() -> str: ...
