#!/usr/bin/env python3
"""Generate shared integer Oklab constants; no runtime floating conversion.

Matrices: https://bottosson.github.io/posts/oklab/ (public-domain option).
sRGB decoding: https://www.w3.org/TR/css-color-4/#color-conversion-code
"""

from decimal import Decimal, ROUND_HALF_UP, localcontext
from pathlib import Path

RGB_TO_LMS = (
    ("0.4122214708", "0.5363325363", "0.0514459929"),
    ("0.2119034982", "0.6806995451", "0.1073969566"),
    ("0.0883024619", "0.2817188376", "0.6299787005"),
)
LMS_TO_LAB = (
    ("0.2104542553", "0.7936177850", "-0.0040720468"),
    ("1.9779984951", "-2.4285922050", "0.4505937099"),
    ("0.0259040371", "0.7827717662", "-0.8086757660"),
)


def rounded(value):
    return int(value.to_integral_value(rounding=ROUND_HALF_UP))


def matrix(rows, sums):
    result = []
    for row, target in zip(rows, sums, strict=True):
        values = [rounded(Decimal(v) * 32768) for v in row]
        largest = max(range(3), key=lambda i: abs(values[i]))
        values[largest] += target * 32768 - sum(values)
        assert sum(values) == target * 32768
        result.append(values)
    return result


def generate():
    with localcontext() as context:
        context.prec = 60
        linear = []
        for byte in range(256):
            value = Decimal(byte) / 255
            decoded = (value / Decimal("12.92") if value <= Decimal("0.04045")
                       else ((value + Decimal("0.055")) / Decimal("1.055")) ** Decimal("2.4"))
            linear.append(rounded(decoded * 65536))
        lms = matrix(RGB_TO_LMS, (1, 1, 1))
        lab = matrix(LMS_TO_LAB, (1, 0, 0))
    assert linear[0] == 0 and linear[-1] == 65536
    assert all(a < b for a, b in zip(linear, linear[1:]))
    assert all(v >= 0 for row in lms for v in row)
    root = Path(__file__).resolve().parents[1]
    header = "// Generated by scripts/generate-oklab.py; see generator for provenance.\n"
    rust = header + "pub(super) const SRGB_LINEAR: [u32; 256] = [\n"
    wgsl = header + "var<private> SRGB_LINEAR: array<u32, 256> = array<u32, 256>(\n"
    for start in range(0, 256, 16):
        values = linear[start:start + 16]
        rust += "    " + ", ".join(map(str, values)) + ",\n"
        wgsl += "    " + ", ".join(f"{v}u" for v in values) + ",\n"
    rust += "];\n"
    wgsl += ");\n"
    for name, rows, kind in (("RGB_TO_LMS", lms, "u32"), ("LMS_TO_LAB", lab, "i32")):
        rust += f"pub(super) const {name}: [[{kind}; 3]; 3] = [\n"
        for i, row in enumerate(rows):
            rust += "    [" + ", ".join(map(str, row)) + "],\n"
            wgsl += f"const {name}_{i}: vec3<{kind}> = vec3<{kind}>(" + ", ".join(map(str, row)) + ");\n"
        rust += "];\n"
    (root / "crates/vestra-core/src/oklab_constants.in").write_text(rust)
    (root / "crates/vestra-render/src/shaders/effects/oklab_constants.wgsl").write_text(wgsl)
    print("Generated 256 sRGB entries and two normalized Q15 matrices")


if __name__ == "__main__":
    generate()
