#!/usr/bin/env python3
"""Reproduce the original toroidal 32x32 void-and-cluster threshold tile."""

import math
from pathlib import Path

SIZE = 32
COUNT = SIZE * SIZE


def generate():
    # Fixed integer shuffle avoids depending on a library PRNG's version.
    order = list(range(COUNT))
    state = 0x5EED
    for i in range(COUNT - 1, 0, -1):
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        j = state % (i + 1)
        order[i], order[j] = order[j], order[i]
    kernel = [
        math.exp(-(min(x, SIZE - x) ** 2 + min(y, SIZE - y) ** 2) / (2 * 1.5**2))
        for y in range(SIZE)
        for x in range(SIZE)
    ]
    weights = [
        [
            kernel[
                ((j // SIZE - i // SIZE) % SIZE) * SIZE + (j % SIZE - i % SIZE) % SIZE
            ]
            for j in range(COUNT)
        ]
        for i in range(COUNT)
    ]
    occupied = [False] * COUNT
    density = [0.0] * COUNT

    def toggle(index, value):
        occupied[index] = value
        sign = 1 if value else -1
        for j, weight in enumerate(weights[index]):
            density[j] += sign * weight

    def cluster():
        return max(
            (i for i in range(COUNT) if occupied[i]), key=lambda i: (density[i], -i)
        )

    def void():
        return min(
            (i for i in range(COUNT) if not occupied[i]), key=lambda i: (density[i], i)
        )

    initial_count = COUNT // 8
    for i in order[:initial_count]:
        toggle(i, True)
    for _ in range(COUNT * 10):
        crowded = cluster()
        toggle(crowded, False)
        empty = void()
        toggle(empty, True)
        if empty == crowded:
            break
    else:
        raise RuntimeError("initial pattern did not converge")
    initial = occupied.copy()
    ranks = [-1] * COUNT
    for rank in range(initial_count - 1, -1, -1):
        i = cluster()
        ranks[i] = rank
        toggle(i, False)
    for i, value in enumerate(initial):
        if value:
            toggle(i, True)
    for rank in range(initial_count, COUNT // 2):
        i = void()
        ranks[i] = rank
        toggle(i, True)
    # Fill the second half by removing clusters from the complement.
    for i in range(COUNT):
        toggle(i, not occupied[i])
    for rank in range(COUNT // 2, COUNT):
        i = cluster()
        ranks[i] = rank
        toggle(i, False)
    assert sorted(ranks) == list(range(COUNT))
    # Low spatial frequencies must be suppressed at multiple tone cutoffs.
    for cutoff in (COUNT // 8, COUNT // 4, COUNT // 2, 3 * COUNT // 4, 7 * COUNT // 8):
        energy = 0.0
        for fx, fy in ((1, 0), (0, 1), (1, 1), (1, -1), (2, 0), (0, 2)):
            real = imaginary = 0.0
            for i, rank in enumerate(ranks):
                if rank < cutoff:
                    angle = 2 * math.pi * (fx * (i % SIZE) + fy * (i // SIZE)) / SIZE
                    real += math.cos(angle)
                    imaginary += math.sin(angle)
            energy += real**2 + imaginary**2
        white_energy = 6 * cutoff * (1 - cutoff / COUNT)
        assert energy < white_energy * 0.1, (cutoff, energy, white_energy)
    return ranks


def main():
    ranks = generate()
    root = Path(__file__).resolve().parents[1] / "crates/vestra-render/src"
    rows = [
        ", ".join(str(value) for value in ranks[i : i + SIZE])
        for i in range(0, COUNT, SIZE)
    ]
    (root / "blue_noise_ranks.in").write_text(
        "// Generated by scripts/generate-blue-noise.py.\n[\n"
        + "\n".join("    " + row + "," for row in rows)
        + "\n]\n"
    )
    (root / "shaders/effects/blue_noise.wgsl").write_text(
        "// Generated by scripts/generate-blue-noise.py.\nvar<private> BLUE_NOISE: array<u32, 1024> = array<u32, 1024>(\n"
        + "\n".join("    " + row + "," for row in rows)
        + "\n);\n"
    )


if __name__ == "__main__":
    main()
